[package]
name = "terminal"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1.31.0", features = ["full"] }
futures = "0.3.28"
log = { version="0.4.20", features=["std"] }

crossterm = { version = "0.27.0", features = ["event-stream"] }
once_cell = "1.18.0"
